/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package MultiSelectComboBox

import java.awt.Dimension
import java.awt.GridBagConstraints
import java.awt.GridBagLayout
import javax.swing.*

fun main() {
    val view = View()
    Controller(view)
    view.isVisible = true
}
