/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package MultiSelectComboBox

fun main() {
    println("test")
    val view = View()
    Controller(view)
    view.isVisible = true
}
